version: '2'
services:
  db:
    build: mysqldb
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - $HOME/.ssh:/root/.ssh
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
